import type { Block, TripView } from "./types";

/**
 * Single shared demo fixture rendered by every skin's gallery tile,
 * so users are comparing chrome — not content.
 */
export const DEMO_TRIP: TripView = {
  destination: "Sample",
  subtitle: "Three slow days along the Tagus.",
  slug: "demo-lisbon",
  start_date: "2026-06-12",
  end_date: "2026-06-14",
  days: 3,
};

/** Structured Lisbon demo. The new view engine reads this as:
 *  flights → preface (hotel + currency) → 3 days × {morning, afternoon, evening}
 *  with rich place metadata (address, phone, website, hours, reservation). */
export const DEMO_BLOCKS: Block[] = [
  // ---- Outbound flight ----
  {
    kind: "flight",
    direction: "outbound",
    airline: "TAP Air Portugal",
    flightNumber: "TP204",
    confirmation: "ABC123",
    from: "JFK",
    to: "LIS",
    fromCity: "New York",
    toCity: "Lisbon",
    date: "Jun 12, 2026",
    arriveDate: "Jun 13, 2026",
    departTime: "20:50",
    arriveTime: "08:35",
    passenger: "Jordan Rivera",
    seat: "14C",
    boardingGroup: "Group 3",
    boardingTime: "20:05",
    fareClass: "Main Cabin",
    baggage: "1 carry-on + 1 checked (23kg)",
    price: "$612.40",
    note: "Direct overnight from JFK. Aisle seat.",
  },

  // ---- Photo gallery (coverflow) — real Wikimedia Commons images with
  //      true licenses, so the attribution affordance is exercised. ----
  {
    kind: "gallery",
    title: "The Trip in Pictures",
    images: [
      {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Lisbon_tram_in_Baixa_Chiado.jpg/960px-Lisbon_tram_in_Baixa_Chiado.jpg",
        alt: "A yellow Lisbon tram climbing through Baixa-Chiado",
        caption: "the trams",
        provider: "wikimedia",
        license: "CC BY 2.0",
        licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
        creator: "Daniel Sparing",
        sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Lisbon_tram_in_Baixa_Chiado.jpg",
      },
      {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Lisbon_tram_speeding_in_Alfama.jpg/960px-Lisbon_tram_speeding_in_Alfama.jpg",
        alt: "Tram threading the narrow streets of Alfama",
        caption: "alfama",
        provider: "wikimedia",
        license: "CC BY 2.0",
        licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
        creator: "Daniel Sparing",
        sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Lisbon_tram_speeding_in_Alfama.jpg",
      },
      {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Alfama_%283903814530%29.jpg/960px-Alfama_%283903814530%29.jpg",
        alt: "Terracotta rooftops of Alfama toward the Tagus",
        caption: "rooftops",
        provider: "wikimedia",
        license: "CC BY 2.0",
        licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
        creator: "Bernt Rostad",
        sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Alfama_(3903814530).jpg",
      },
      {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Lisbon_Torre_de_Bel%C3%A9m_BW_2018-10-03_16-35-17.jpg/960px-Lisbon_Torre_de_Bel%C3%A9m_BW_2018-10-03_16-35-17.jpg",
        alt: "Torre de Belém on the river at golden hour",
        caption: "belém",
        provider: "wikimedia",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        creator: "Berthold Werner",
        sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Lisbon_Torre_de_Bel%C3%A9m_BW_2018-10-03_16-35-17.jpg",
      },
      {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Azulejo_Lisboa_Portugal.jpg/960px-Azulejo_Lisboa_Portugal.jpg",
        alt: "Blue-and-white azulejo tilework",
        caption: "azulejo",
        provider: "wikimedia",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        creator: "LightWord",
        sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Azulejo_Lisboa_Portugal.jpg",
      },
      {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Arco_Triunfal_da_Rua_Augusta%2C_Plaza_del_Comercio%2C_Lisboa%2C_Portugal%2C_2012-05-12%2C_DD_02.JPG/960px-Arco_Triunfal_da_Rua_Augusta%2C_Plaza_del_Comercio%2C_Lisboa%2C_Portugal%2C_2012-05-12%2C_DD_02.JPG",
        alt: "Rua Augusta Arch over Praça do Comércio",
        caption: "the square",
        provider: "wikimedia",
        license: "CC BY-SA 3.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
        creator: "Diego Delso",
        sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Arco_Triunfal_da_Rua_Augusta,_Plaza_del_Comercio,_Lisboa,_Portugal,_2012-05-12,_DD_02.JPG",
      },
    ],
  },

  // ---- Trip essentials (preface) ----
  {
    kind: "place",
    name: "Memmo Príncipe Real",
    lat: 38.716,
    lng: -9.1476,
    category: "accommodation",
    address: "Rua D. Pedro V 56, 1250-094 Lisboa",
    phone: "+351 21 901 6800",
    website: "https://www.memmohotels.com/principereal",
    websiteTitle: "Memmo Príncipe Real",
    checkIn: "15:00",
    checkOut: "12:00",
    amenities: "Rooftop bar · breakfast included · gym",
    reservation: "Conf #MPR-44218 · 2 nights",
    note: "Quiet courtyard, rooftop bar.",
  },
  {
    kind: "place",
    name: "Euro · EUR",
    category: "currency",
    note: "≈ 1 USD = 0.92 EUR. Most tascas are cash only.",
  },
  {
    kind: "place",
    name: "Casa Boma · Lapa Studio",
    lat: 38.7089,
    lng: -9.162,
    category: "accommodation",
    address: "R. do Quelhas 6, 1200-781 Lisboa",
    phone: "+351 21 396 2200",
    website: "https://casaboma.com",
    websiteTitle: "Casa Boma",
    checkIn: "16:00",
    checkOut: "11:00",
    amenities: "Self check-in · kitchenette · river view",
    reservation: "Conf #CB-7741 · 1 night (Day 3)",
    note: "Final-night studio closer to the airport.",
  },

  // ============================================================
  // DAY 1
  // ============================================================
  {
    kind: "day",
    n: 1,
    label: "Arrival & Aperitivo",
    images: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Arco_Triunfal_da_Rua_Augusta%2C_Plaza_del_Comercio%2C_Lisboa%2C_Portugal%2C_2012-05-12%2C_DD_02.JPG/960px-Arco_Triunfal_da_Rua_Augusta%2C_Plaza_del_Comercio%2C_Lisboa%2C_Portugal%2C_2012-05-12%2C_DD_02.JPG", alt: "Rua Augusta Arch over Praça do Comércio", provider: "wikimedia", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", creator: "Diego Delso", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Arco_Triunfal_da_Rua_Augusta,_Plaza_del_Comercio,_Lisboa,_Portugal,_2012-05-12,_DD_02.JPG" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Lisbon_tram_in_Baixa_Chiado.jpg/960px-Lisbon_tram_in_Baixa_Chiado.jpg", alt: "A yellow Lisbon tram climbing through Baixa-Chiado", provider: "wikimedia", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", creator: "Daniel Sparing", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Lisbon_tram_in_Baixa_Chiado.jpg" },
    ],
    notes: "Land, drop bags, ease into the city. Sunset at the miradouro.",
  },
  { kind: "section", title: "Morning", partOfDay: "morning" },
  {
    kind: "place",
    name: "Taxi · Lisbon Airport → Príncipe Real",
    category: "transit",
    time: "09:15",
    phone: "+351 21 811 9000",
    vendor: "Cooltra Taxi",
    pickup: "LIS Terminal 1, Arrivals",
    dropoff: "Rua D. Pedro V 56",
    duration: "~25 min",
    note: "Cooltra Taxi · ~€18 · 25 min",
  },
  {
    kind: "place",
    name: "Hello, Kristof",
    lat: 38.7095,
    lng: -9.1524,
    category: "restaurant",
    time: "10:30",
    address: "R. do Poço dos Negros 103",
    phone: "+351 21 802 0103",
    website: "https://hellokristof.com",
    websiteTitle: "Hello, Kristof",
    hours: "Mon–Sun 09:00–18:00",
    dressCode: "Casual",
    mustOrder: "Flat white + carrot cake",
    note: "Flat white + carrot cake.",
  },
  { kind: "section", title: "Afternoon", partOfDay: "afternoon" },
  {
    kind: "place",
    name: "Lunch · Time Out Market",
    lat: 38.7069,
    lng: -9.146,
    category: "restaurant",
    time: "13:00",
    address: "Av. 24 de Julho 49",
    website: "https://www.timeoutmarket.com/lisboa",
    websiteTitle: "Time Out Market Lisboa",
    hours: "10:00–24:00",
    dressCode: "Casual",
    mustOrder: "Henrique Sá Pessoa's prego",
  },
  {
    kind: "place",
    name: "Walk · Príncipe Real → Bairro Alto",
    category: "walk",
    time: "15:00",
    trailhead: "Praça do Príncipe Real",
    distance: "1.6 km",
    duration: "~25 min",
    difficulty: "Easy",
    waypoints: "Embaixada concept store · Miradouro de São Pedro",
    prep: "Cobblestones — comfortable shoes.",
    note: "About 25 min. Stop at bookshop Ler Devagar if it's open.",
  },
  { kind: "section", title: "Evening", partOfDay: "evening" },
  {
    kind: "place",
    name: "Aperitivo · Pensão Amor",
    lat: 38.7073,
    lng: -9.1437,
    category: "restaurant",
    time: "19:00",
    address: "R. do Alecrim 19",
    phone: "+351 21 314 3399",
    dressCode: "Smart casual",
    mustOrder: "Vermouth tonic",
  },
  {
    kind: "place",
    name: "Dinner · Belcanto",
    lat: 38.7097,
    lng: -9.1421,
    category: "restaurant",
    time: "21:00",
    address: "Largo de São Carlos 10",
    phone: "+351 21 342 0607",
    website: "https://belcanto.pt",
    websiteTitle: "Belcanto",
    dressCode: "Jacket optional",
    mustOrder: "Tasting menu, Dom Rodrigo finale",
    reservation: "Conf #BEL-882 · party of 2",
    note: "Tasting menu · jacket not required.",
  },

  // ============================================================
  // DAY 2
  // ============================================================
  {
    kind: "day",
    n: 2,
    label: "The Long Walk",
    notes: "Tile museum, market lunch, nap, fado after dark.",
  },
  { kind: "section", title: "Morning", partOfDay: "morning" },
  {
    kind: "place",
    name: "Museu Nacional do Azulejo",
    lat: 38.7247,
    lng: -9.1136,
    images: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Azulejo_Lisboa_Portugal.jpg/960px-Azulejo_Lisboa_Portugal.jpg", alt: "Blue-and-white azulejo tilework", provider: "wikimedia", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", creator: "LightWord", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Azulejo_Lisboa_Portugal.jpg" },
    ],
    category: "culture",
    time: "10:00",
    address: "R. Madre de Deus 4",
    phone: "+351 21 810 0340",
    website: "https://www.museudoazulejo.gov.pt",
    websiteTitle: "Museu Nacional do Azulejo",
    hours: "Tue–Sun 10:00–18:00 · closed Mon",
    ticketRequirement: "Walk-in · €5",
    duration: "~90 min",
    tourDetails: "Audio guide €2 at desk",
  },
  { kind: "section", title: "Afternoon", partOfDay: "afternoon" },
  {
    kind: "place",
    name: "Lunch · A Cevicheria",
    lat: 38.7157,
    lng: -9.1481,
    category: "restaurant",
    time: "13:30",
    address: "R. Dom Pedro V 129",
    phone: "+351 21 803 8815",
    dressCode: "Casual",
    mustOrder: "Octopus tiradito",
    note: "Walk-in only. Octopus tiradito.",
  },
  {
    kind: "place",
    name: "Castelo de São Jorge",
    lat: 38.7139,
    lng: -9.1335,
    images: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Castelo_de_S%C3%A3o_Jorge%2C_Lisboa_03.jpg/960px-Castelo_de_S%C3%A3o_Jorge%2C_Lisboa_03.jpg", alt: "Ramparts of Castelo de São Jorge", provider: "wikimedia", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", creator: "Simon Burchell", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Castelo_de_S%C3%A3o_Jorge,_Lisboa_03.jpg" },
    ],
    category: "culture",
    time: "16:00",
    address: "R. de Santa Cruz do Castelo",
    hours: "09:00–21:00",
    ticketRequirement: "Pre-booked entry · €15",
    duration: "~2h",
    tourDetails: "Self-guided · Camera Obscura tours on the hour",
  },
  {
    kind: "place",
    name: "Walk · Alfama miradouro loop",
    images: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Alfama_%283903814530%29.jpg/960px-Alfama_%283903814530%29.jpg", alt: "Terracotta rooftops of Alfama toward the Tagus", provider: "wikimedia", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", creator: "Bernt Rostad", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Alfama_(3903814530).jpg" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Lisbon_tram_speeding_in_Alfama.jpg/960px-Lisbon_tram_speeding_in_Alfama.jpg", alt: "Tram threading the narrow streets of Alfama", provider: "wikimedia", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", creator: "Daniel Sparing", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Lisbon_tram_speeding_in_Alfama.jpg" },
    ],
    category: "walk",
    time: "18:00",
    trailhead: "Largo das Portas do Sol",
    distance: "2.1 km",
    duration: "~45 min",
    difficulty: "Moderate",
    waypoints: "Miradouro de Santa Luzia · Sé de Lisboa · Chafariz d'El Rei",
    prep: "Steep cobblestones — go before dinner, not after.",
  },
  { kind: "section", title: "Evening", partOfDay: "evening" },
  {
    kind: "place",
    name: "Fado at Mesa de Frades",
    lat: 38.7128,
    lng: -9.1256,
    category: "event",
    time: "21:30",
    address: "R. dos Remédios 139",
    phone: "+351 91 702 9436",
    venue: "Mesa de Frades (former chapel)",
    doorOpen: "21:00",
    ticketLink: "https://mesadefrades.com",
    ticketLinkTitle: "Mesa de Frades",
    seat: "Table 4 · banquette",
    venueRules: "No flash photography · cash bar",
    reservation: "Conf #MDF-117 · two seatings",
  },

  // ============================================================
  // DAY 3
  // ============================================================
  {
    kind: "day",
    n: 3,
    label: "Slow Departure",
    notes: "Pastel from Manteigaria. LX Factory. Train to airport at four — tickets at https://www.cp.pt.",
    linkTitles: { "https://www.cp.pt": "Comboios de Portugal" },
  },
  { kind: "section", title: "Morning", partOfDay: "morning" },
  {
    kind: "place",
    name: "Pastéis · Manteigaria",
    images: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Pastel_De_Nata.jpg/960px-Pastel_De_Nata.jpg", alt: "Pastel de nata with a blistered top", provider: "wikimedia", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", creator: "TheDumpy", sourcePageUrl: "https://commons.wikimedia.org/wiki/File:Pastel_De_Nata.jpg" },
    ],
    category: "restaurant",
    time: "09:00",
    address: "R. do Loreto 2",
    hours: "08:00–24:00",
    dressCode: "Counter-service",
    mustOrder: "Pastel de nata, still warm",
  },
  { kind: "section", title: "Afternoon", partOfDay: "afternoon" },
  {
    kind: "place",
    name: "LX Factory",
    category: "culture",
    time: "13:00",
    address: "R. Rodrigues de Faria 103",
    ticketRequirement: "Free entry · shops priced individually",
    duration: "~2h",
    tourDetails: "Self-guided · Ler Devagar bookstore is the anchor",
    note: "Lunch at A Praça. Browse Ler Devagar.",
  },
  {
    kind: "place",
    name: "Aerobus to LIS",
    category: "transit",
    time: "16:00",
    vendor: "Aerobus Line 1",
    pickup: "Cais do Sodré stop",
    dropoff: "Lisbon Airport Terminal 1",
    duration: "~35 min",
    website: "https://www.aerobus.pt",
    note: "€4 · 35 min · last stop is Terminal 1.",
  },
  { kind: "section", title: "Evening", partOfDay: "evening" },
  {
    kind: "place",
    name: "Sunset Concert · Hot Clube de Portugal",
    category: "event",
    time: "17:30",
    address: "Praça da Alegria 48",
    venue: "Hot Clube de Portugal",
    doorOpen: "17:00",
    ticketLink: "https://hcp.pt",
    seat: "Standing · main room",
    venueRules: "Cash bar · phones on silent",
    note: "Skip kiosk; counters open 3h before departure.",
  },

  // ---- Inbound flight ----
  {
    kind: "flight",
    direction: "inbound",
    airline: "TAP Air Portugal",
    flightNumber: "TP203",
    confirmation: "DEF456",
    from: "LIS",
    to: "JFK",
    fromCity: "Lisbon",
    toCity: "New York",
    date: "Jun 14, 2026",
    departTime: "20:30",
    arriveTime: "23:15",
    passenger: "Jordan Rivera",
    note: "Window. Arrive same day NYC.",
  },
];