import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/api/public/google/start")({
  server: {
    handlers: {
      // Legacy entry — the OAuth URL is now generated by the
      // getGoogleAuthUrl server function and the client redirects directly
      // to Google. Anything that lands here should bounce to /app so the
      // user can re-trigger the connect flow with a valid session.
      GET: async () =>
        new Response(null, {
          status: 302,
          headers: { Location: "/app?drive=error&msg=use_connect_button" },
        }),
    },
  },
});