/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as E2eKanbanRouteImport } from './routes/e2e.kanban'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as TemplatesIdPreviewRouteImport } from './routes/templates_.$id.preview'
import { Route as ApiPublicHooksCleanupPendingDocExportsRouteImport } from './routes/api/public/hooks/cleanup-pending-doc-exports'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eKanbanRoute = E2eKanbanRouteImport.update({
  id: '/e2e/kanban',
  path: '/e2e/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TemplatesIdPreviewRoute = TemplatesIdPreviewRouteImport.update({
  id: '/templates_/$id/preview',
  path: '/templates/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupPendingDocExportsRoute =
  ApiPublicHooksCleanupPendingDocExportsRouteImport.update({
    id: '/api/public/hooks/cleanup-pending-doc-exports',
    path: '/api/public/hooks/cleanup-pending-doc-exports',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/app': typeof AuthenticatedAppRoute
  '/e2e/kanban': typeof E2eKanbanRoute
  '/t/$slug': typeof TSlugRoute
  '/templates/$id/preview': typeof TemplatesIdPreviewRoute
  '/api/public/hooks/cleanup-pending-doc-exports': typeof ApiPublicHooksCleanupPendingDocExportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/app': typeof AuthenticatedAppRoute
  '/e2e/kanban': typeof E2eKanbanRoute
  '/t/$slug': typeof TSlugRoute
  '/templates/$id/preview': typeof TemplatesIdPreviewRoute
  '/api/public/hooks/cleanup-pending-doc-exports': typeof ApiPublicHooksCleanupPendingDocExportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/e2e/kanban': typeof E2eKanbanRoute
  '/t/$slug': typeof TSlugRoute
  '/templates_/$id/preview': typeof TemplatesIdPreviewRoute
  '/api/public/hooks/cleanup-pending-doc-exports': typeof ApiPublicHooksCleanupPendingDocExportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/plan'
    | '/sitemap.xml'
    | '/templates'
    | '/app'
    | '/e2e/kanban'
    | '/t/$slug'
    | '/templates/$id/preview'
    | '/api/public/hooks/cleanup-pending-doc-exports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/plan'
    | '/sitemap.xml'
    | '/templates'
    | '/app'
    | '/e2e/kanban'
    | '/t/$slug'
    | '/templates/$id/preview'
    | '/api/public/hooks/cleanup-pending-doc-exports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/plan'
    | '/sitemap.xml'
    | '/templates'
    | '/_authenticated/app'
    | '/e2e/kanban'
    | '/t/$slug'
    | '/templates_/$id/preview'
    | '/api/public/hooks/cleanup-pending-doc-exports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  E2eKanbanRoute: typeof E2eKanbanRoute
  TSlugRoute: typeof TSlugRoute
  TemplatesIdPreviewRoute: typeof TemplatesIdPreviewRoute
  ApiPublicHooksCleanupPendingDocExportsRoute: typeof ApiPublicHooksCleanupPendingDocExportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/kanban': {
      id: '/e2e/kanban'
      path: '/e2e/kanban'
      fullPath: '/e2e/kanban'
      preLoaderRoute: typeof E2eKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/templates_/$id/preview': {
      id: '/templates_/$id/preview'
      path: '/templates/$id/preview'
      fullPath: '/templates/$id/preview'
      preLoaderRoute: typeof TemplatesIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-pending-doc-exports': {
      id: '/api/public/hooks/cleanup-pending-doc-exports'
      path: '/api/public/hooks/cleanup-pending-doc-exports'
      fullPath: '/api/public/hooks/cleanup-pending-doc-exports'
      preLoaderRoute: typeof ApiPublicHooksCleanupPendingDocExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  E2eKanbanRoute: E2eKanbanRoute,
  TSlugRoute: TSlugRoute,
  TemplatesIdPreviewRoute: TemplatesIdPreviewRoute,
  ApiPublicHooksCleanupPendingDocExportsRoute:
    ApiPublicHooksCleanupPendingDocExportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
