import type { GuideDef } from "./types";

/**
 * Insider Guide № 09 — Mexico City. Editorial copy is preserved verbatim from
 * the founder-approved source; "verify before publish" notes live in
 * docs/guides-verification.md, never in rendered content.
 */
export const mexicoCity: GuideDef = {
  slug: "mexico-city",
  destination: "Mexico City",
  title: "Mexico City: The Insider Guide",
  seoTitle: "Mexico City Itinerary — 5 Days: The Insider Guide | TravelDoss",
  dek: "The food-and-design capital of the moment, at 7,350 feet.",
  metaDescription:
    "A 5-day Mexico City itinerary: Roma and Condesa, Centro's murals, Barragán, Coyoacán and Teotihuacán — plus the taco tier, where to stay and when to go.",
  days: "5 days",
  season: "November–April",
  no: "№ 09",
  chips: ["5 days", "Food-first", "Dry season"],
  skinId: "cassian",
  accent: "#FF4FA3",
  lat: 19.43,
  lon: -99.13,
  publishedAt: "2026-08-13",
  updatedAt: "2026-08-13",
  published: true,
  faq: [
    {
      q: "Is Mexico City safe for travelers?",
      a: "In the visitor core, yes — standard megacity rules: ride-hail at night, pickpocket awareness in Centro and the Metro. The overwhelming majority of trips pass without incident.",
    },
    {
      q: "How many days do you need?",
      a: "Five: three for the city, one for Coyoacán and the south, one for Teotihuacán or Xochimilco.",
    },
    {
      q: "Where should you stay?",
      a: "Roma Norte or Condesa for walkable, leafy, restaurant-dense first visits; Polanco for quiet luxury; Círculo Mexicano in Centro for design pilgrims.",
    },
  ],
  sources:
    "Sources: Roadbook CDMX (restaurants '25, bars '26), The Infatuation ('25), Eater canon, Michelin Guide Mexico (stars + Keys '25), World's 50 Best (Handshake #1), CNT + T+L (museums, hotels), Casa Luis Barragán official ticketing, Viva La Travelista (Xochimilco '25), Forbes (design shops '26, Art Week), Pearl (Pujol booking '26), Travel Guard/BHTP (safety '25–26).",
  blocks: [
    {
      kind: "hero",
      eyebrow: "Insider Guide № 09",
      title: "Mexico City: The Insider Guide",
      subtitle: "The food-and-design capital of the moment, at 7,350 feet.",
    },
    {
      kind: "paragraph",
      text: "The numbers say what locals have known for a decade: restaurant search interest at a ten-year high, Michelin stars across the Polanco tasting rooms (and, for two years, a taco stand), two of the World's 50 Best, and a design scene that runs from Barragán's pink walls to the Sunday chaos of Lagunilla's antiques. Mexico City is the new Paris with better lunch. It rewards planners — altitude, distance, and reservation lead times all punish the improviser. Five days, based in Roma or Condesa. Book the big three (Pujol, Contramar, Casa Barragán) before you book anything else.",
    },
    {
      kind: "day",
      n: 1,
      label: "Day 1 — Roma & Condesa (base camp)",
    },
    {
      kind: "place",
      name: "Parque México loop",
      time: "Morning",
      category: "walk",
      note: "Art-deco balconies, dog academies, the city at its most walkable.",
    },
    {
      kind: "place",
      name: "Contramar",
      time: "Lunch",
      category: "restaurant",
      note: "Tuna tostadas and the pink-and-white fish that made the room famous. Reservations open about a month out on OpenTable and evaporate; otherwise walk in at the 12:30 opening.",
    },
    {
      kind: "place",
      name: "Gallery hop",
      time: "Afternoon",
      category: "culture",
      note: "OMR, Casa Lamm.",
    },
    {
      kind: "place",
      name: "Licorería Limantour",
      time: "Night",
      category: "restaurant",
      note: "A world's-50-best fixture — or Baltra.",
    },
    {
      kind: "day",
      n: 2,
      label: "Day 2 — Centro Histórico",
    },
    {
      kind: "place",
      name: "Zócalo and Templo Mayor",
      time: "Morning",
      category: "culture",
      note: "The Aztec city surfacing through the Spanish one.",
    },
    {
      kind: "place",
      name: "El Cardenal",
      time: "First",
      category: "restaurant",
      note: "The power breakfast: hot chocolate, nata, chilaquiles.",
    },
    {
      kind: "place",
      name: "Diego Rivera murals",
      time: "Afternoon",
      category: "culture",
      note: "Palacio Nacional and SEP. Palacio de Bellas Artes at golden hour.",
    },
    {
      kind: "place",
      name: "La Ópera cantina",
      time: "Evening",
      category: "restaurant",
      note: "Bullet hole in the ceiling, allegedly Pancho Villa's.",
    },
    {
      kind: "day",
      n: 3,
      label: "Day 3 — Chapultepec & Polanco",
    },
    {
      kind: "place",
      name: "Museo Nacional de Antropología",
      time: "At opening",
      category: "culture",
      note: "Three hours minimum; the Sun Stone and the Oaxaca rooms. Closed Mondays.",
    },
    {
      kind: "place",
      name: "Chapultepec Castle",
      time: "Late morning",
      category: "culture",
      note: "The only royal castle in the Americas.",
    },
    {
      kind: "place",
      name: "Casa Luis Barragán",
      time: "Afternoon",
      category: "culture",
      note: "Timed visits only — guided or the newer self-guided format; tickets release in batches on the official site and sell out fast. Book four to six weeks ahead.",
    },
    {
      kind: "place",
      name: "Casa Pedregal and Casa Gilardi",
      time: "Optional",
      category: "culture",
      tier: "shadow",
      note: "If you missed it, Casa Pedregal and Casa Gilardi are the \"other Barragáns\" with humane booking.",
    },
    {
      kind: "place",
      name: "Pujol or Quintonil",
      time: "Dinner",
      category: "restaurant",
      note: "Book Pujol at the three-month mark; fifteen minutes late forfeits the table. Ticuchi, Olvera's moody agave bar, is the consolation prize that isn't one.",
    },
    {
      kind: "day",
      n: 4,
      label: "Day 4 — Coyoacán & San Ángel",
    },
    {
      kind: "place",
      name: "Casa Azul",
      time: "Morning",
      category: "culture",
      note: "First timed slot, bought online two to four weeks ahead; walk-ups don't exist.",
    },
    {
      kind: "place",
      name: "Mercado de Coyoacán",
      time: "Midday",
      category: "restaurant",
      note: "Tostadas, the plazas.",
    },
    {
      kind: "place",
      name: "Anahuacalli",
      time: "Midday",
      category: "culture",
      note: "Rivera's volcanic-stone temple to his own collection.",
    },
    {
      kind: "place",
      name: "Bazar Sábado in San Ángel",
      time: "Afternoon",
      category: "culture",
      tier: "shadow",
      note: "Saturday? The craft market that justifies the word.",
    },
    {
      kind: "place",
      name: "Expendio de Maíz",
      time: "Early dinner",
      category: "restaurant",
      note: "No menu, no reservations, heirloom corn; arrive early and surrender.",
    },
    {
      kind: "day",
      n: 5,
      label: "Day 5 — Dawn pyramids or Sunday city",
    },
    {
      kind: "place",
      name: "Teotihuacán at 8am opening",
      time: "Dawn",
      category: "culture",
      note: "Or from a sunrise balloon — before the heat and the buses. Pyramids are no longer climbable; the Avenue of the Dead doesn't need them.",
    },
    {
      kind: "place",
      name: "Lagunilla antiques market",
      time: "Sunday",
      category: "culture",
      tier: "shadow",
      note: "Or, if it's Sunday: 10am–1pm, dealers and stall-side cocktails — then Xochimilco.",
    },
    {
      kind: "place",
      name: "Xochimilco",
      time: "Sunday",
      category: "culture",
      tier: "shadow",
      note: "The verdict is: worth it, correctly managed. Embrace the Sunday party trajineras, or go weekday-morning quiet from Embarcadero Nativitas. Fixed municipal boat rates, ~600 MXN/hour.",
    },
    {
      kind: "note",
      text: "The taco tier, at every hour: El Califa de León (the stand that won — then lost — its Michelin star; the gaonera and the queue don't care), Taquería Orinoco (al pastor until 3:30am), El Vilsito (mechanic shop by day, pastor temple by night). Bars to close: Handshake — currently the best bar in the world on the official list — then Salón Rosetta above Reygadas' mansion, Tlécan for agave in Roma.",
    },
    {
      kind: "note",
      text: "Where to stay — Casa Polanco: two Michelin Keys; a 1940s Spanish Revival mansion done quietly. Four Seasons CDMX: the Reforma hacienda courtyard; list perennial. Círculo Mexicano (Centro): Grupo Habita's Shaker-minimal rooms with a rooftop staring at the cathedral. Octavia Casa (Condesa): one Key; fashion-label minimalism. La Valise (Roma): one Key, three suites, beds that roll onto the terrace. Condesa DF: the scene-y classic that started it all.",
    },
    {
      kind: "note",
      text: "When to go — November–April is the dry prime; late February–March adds the jacarandas — purple streets for free. Rainy season (May–October) means clear mornings and a punctual 4–7pm downpour; plan museums accordingly. Art Week (early February) and Día de Muertos spike hotels. Altitude is real: 7,350 feet — hydrate, and respect the mezcal on night one.",
    },
    {
      kind: "note",
      text: "The practical part — Uber/DiDi everywhere, never street hails; keep the phone off the curb; Centro empties late — leave with it. The safety math in visitor neighborhoods (Roma, Condesa, Polanco, Coyoacán) resembles any large US city: petty theft, not violence, is the realistic risk. Book in this order: Pujol (3 months) → Casa Barragán (4–6 weeks) → Casa Azul (2–4 weeks) → Contramar (1 month) → flights around what you got.",
    },
  ],
};
