import type { GuideDef } from "./types";

/** Insider Guide № 05 — Savannah. Copy preserved verbatim from the source. */
export const savannah: GuideDef = {
  slug: "savannah",
  destination: "Savannah",
  title: "Savannah: The Insider Guide",
  seoTitle: "Savannah Itinerary — 3 Days: The Insider Guide | TravelDoss",
  dek: "The Gothic postcard is real. Come for the second act.",
  metaDescription:
    "A 3-day Savannah itinerary: the squares at 8am, the Starland food scene, the moss-and-marsh islands arc, plus where to stay and when to go.",
  days: "3–4 days",
  season: "Late October–November",
  no: "№ 05",
  chips: ["3–4 days", "Walkable", "Late Oct–Nov"],
  skinId: "marguerite",
  accent: "#9FE08A",
  lat: 32.08,
  lon: -81.09,
  publishedAt: "2026-08-12",
  updatedAt: "2026-08-12",
  published: true,
  faq: [
    {
      q: "When is the best time to visit Savannah?",
      a: "Late October–November: clear, cool, unhumid — the local answer. March–April is azalea season at peak prices; summer is a feels-like-103° walking city.",
    },
    {
      q: "How many days do you need in Savannah?",
      a: "Three walkable days — Historic District, Starland, and the moss-and-marsh arc — with an optional fourth for Tybee Island.",
    },
    {
      q: "Do you need a car in Savannah?",
      a: "Not until Day 3. The Historic District and Starland sit on one flat 2.5-mile spine with a free shuttle; rent or rideshare only for Bonaventure, Wormsloe, and the islands.",
    },
  ],
  sources:
    "Sources: Garden & Gun (Savannah refresh Apr/May 2026; 2022–2024 guides; Gullah Geechee coverage), Eater (The Grey, Restaurant of the Year; Grey Market; Husk), Travel + Leisure (It List 2024 Bardo, It List 2026 Municipal Grand, World's Best 2023–25 Perry Lane), Condé Nast Traveler (Hot List 2024 Bardo; Readers' Choice small-city rankings), AFAR (Savannah things-to-do, Apr 2026), Indagare (Savannah hotels + Book Lady), Ciao Bambino (family guide), Robb Report (Perry Lane), Resy (The Grey team's insider guide; Best of Savannah 2024), Thrillist (Hotel Bardo 2024; \"Artistic Heart of the South\" 2021), Cool Hunting (SCAD/Paula Wallace lens), Savannah First-Timer's Guide, Atlas Obscura (Pin Point).",
  blocks: [
    {
      kind: "hero",
      eyebrow: "Insider Guide № 05",
      title: "Savannah: The Insider Guide",
      subtitle: "The Gothic postcard is real. Come for the second act.",
    },
    {
      kind: "paragraph",
      text: "Yes: the squares, the Spanish moss, the cemetery statuary at golden hour — all of it delivers exactly as promised. But the reason to book the flight is what's happened since the postcard: a small city now eating and designing far above its weight. A James Beard-winning kitchen in a segregation-era bus terminal. A Michelin-starred chef frying chicken in the Starland District. Design hotels on Forsyth Park, a Death & Co bar in a midcentury bank, and an art school that quietly runs the whole aesthetic. Michelin's new American South guide skipped Savannah entirely, which locals took as the insult and the compliment it is — this is the best un-starred food city in the South.",
    },
    { kind: "paragraph", text: "Three days, walkable. A fourth if the beach calls." },
    {
      kind: "day",
      n: 1,
      label: "Day 1 — The Historic District",
      notes: "Work the postcard first, on foot, before the trolleys wake up.",
    },
    {
      kind: "place",
      name: "The squares at 8am",
      time: "Morning",
      category: "walk",
      note: "Jones Street's live-oak tunnel, Madison, Chippewa. Two miles of the best urban planning in America, empty except for dog walkers.",
    },
    {
      kind: "place",
      name: "Owens-Thomas House & Slave Quarters",
      time: "Midday",
      category: "culture",
      note: "The house museum that tells the whole story, including the enslaved people who ran it. The single most important ticket downtown. Timed entry; daytime.",
    },
    {
      kind: "place",
      name: "Forsyth Park",
      time: "Midday",
      category: "walk",
      note: "The fountain for the photo, the south end for the life. Saturday means the Forsyth Farmers' Market, which The Grey's own team calls their weekend ritual.",
    },
    {
      kind: "place",
      name: "Alex Raskin Antiques",
      time: "Afternoon",
      category: "culture",
      note: "Four crumbling floors of a Bull Street mansion, everything for sale, nothing restored. The most photogenic retail in Georgia.",
    },
    {
      kind: "place",
      name: "The Book Lady",
      time: "Afternoon",
      category: "culture",
      note: "On Liberty — the indie bookstore, since 1978, for the flight home.",
    },
    {
      kind: "place",
      name: "The Grey",
      time: "Dinner",
      category: "restaurant",
      note: "Mashama Bailey's port-city Southern cooking in the restored 1938 Greyhound station; Eater's national Restaurant of the Year, Chef's Table, all of it earned. Book weeks out — or walk in solo and eat at the bar, which is the insider setting anyway. Fallback that isn't a fallback: Common Thread, produce-driven fine dining in a Victorian mansion.",
    },
    {
      kind: "place",
      name: "The Original Pinkie Masters",
      time: "Evening",
      category: "restaurant",
      note: "Nightcap: the midcentury political dive where Jimmy Carter announced from the bar. Cash, jukebox, no speeches required.",
    },
    {
      kind: "day",
      n: 2,
      label: "Day 2 — Design District & Starland",
      notes: "The SCAD day. The art school is the city's engine; today you drive it.",
    },
    {
      kind: "place",
      name: "Whitaker Street \"Design District\"",
      time: "Late morning",
      category: "culture",
      note: "shopSCAD (everything student- or alum-made) and the SCAD Museum of Art, the best contemporary museum between Miami and DC.",
    },
    {
      kind: "place",
      name: "Starland District",
      time: "Afternoon",
      category: "walk",
      note: "Bull Street from 37th to Victory: murals, Graveface Records, House of Strut vintage, Laney Contemporary if a show is up (check the calendar; it's the city's serious gallery).",
    },
    {
      kind: "place",
      name: "Starland Yard",
      time: "Afternoon",
      category: "restaurant",
      note: "For a casual hour — Vittoria's Neapolitan pies from a chef who cooked in Naples, food trucks, picnic tables.",
    },
    {
      kind: "place",
      name: "Brochu's Family Tradition",
      time: "Dinner",
      category: "restaurant",
      note: "A Michelin-starred chef's fried-chicken supper club. Order the bird, the crème brûlée pie, and accept the Jäger shot tradition with dignity. Reserve.",
    },
    {
      kind: "place",
      name: "The Starland bar crawl",
      time: "Evening",
      category: "restaurant",
      note: "Moodright's (duckpin bowling dive) → Over Yonder (cowboy) → Lone Wolf Lounge (tropical). Or the new-guard pick: Late Air, the natural-wine bar in Habersham the city's chefs drink at. Design-hotel option: the \"Infinite Negroni\" at Hotel Bardo on Forsyth, or whatever the Death & Co team is pouring at the Municipal Grand — freshly named to Travel + Leisure's It List of the world's best new hotels for 2026.",
    },
    {
      kind: "day",
      n: 3,
      label: "Day 3 — Moss & Marsh (the islands road)",
      notes: "Get the car. Three stops, one arc east of town, all before lunch beats the heat.",
    },
    {
      kind: "place",
      name: "Bonaventure Cemetery",
      time: "Morning",
      category: "culture",
      note: "Bluff over the Wilmington River, live oaks, moss, marble. Morning light turns it silver. Skip the tour; wander. Free.",
    },
    {
      kind: "place",
      name: "Wormsloe",
      time: "Morning",
      category: "culture",
      note: "The mile-and-a-half avenue of 400 live oaks. The most photographed drive in coastal Georgia, and still under-rated in person. Right after Bonaventure, before the buses.",
    },
    {
      kind: "place",
      name: "Pin Point Heritage Museum",
      time: "Late morning",
      category: "culture",
      note: "A former oyster cannery on Moon River, run by the Gullah Geechee community whose story it tells. Thirty minutes here reframes the whole coast. Limited days — typically Thu–Sat.",
    },
    {
      kind: "place",
      name: "Sandfly BBQ or The Wyld",
      time: "Lunch",
      category: "restaurant",
      note: "Lunch out on the islands: dock seating, shrimp that were swimming this morning.",
    },
    {
      kind: "place",
      name: "Bar Julian",
      time: "Golden hour",
      category: "restaurant",
      note: "Rooftop at the Thompson hotel, Eastern Wharf — the best sunset view in the city, happy hour 2–6pm.",
    },
    {
      kind: "place",
      name: "Narobia's Grits & Gravy",
      time: "Breakfast",
      category: "restaurant",
      tier: "shadow",
      note: "Breakfast worth the queue before any of this: Gullah Geechee whiting and grits, no ceremony. Skip: the River Street chain gauntlet, and note Lady & Sons closed in 2025 — the era is over, the food got better.",
    },
    {
      kind: "day",
      n: 4,
      label: "Day 4 (optional) — Tybee Island",
      notes:
        "Thirty to forty minutes east: wide Atlantic beach, the black-and-white lighthouse, and Sea Wolf for oysters and a Wagyu hot dog with the locals. Alternatively: Beaufort or Bluffton, SC — the Lowcountry's slow towns — each about an hour.",
    },
    {
      kind: "note",
      text: "Where to stay — Savannah's hotel decade has been loud, and the awards agree on the order. 1. Hotel Bardo — the most-decorated: T+L It List 2024, Condé Nast Traveler Hot List 2024, Readers' Choice Top 25 in the South two years running, a Michelin Key. On Forsyth Park, which is exactly where you want to wake up. 2. Perry Lane Hotel (Luxury Collection) — T+L's #1 hotel in Savannah three consecutive years (2023–2025). The polished classic; also the family pick — rooftop pool, house car. 3. Municipal Grand — T+L It List 2026; midcentury bank turned 44-room design hotel with the Death & Co bar downstairs. The newcomer with the best story. 4. Thompson Savannah — Eastern Wharf, Michelin-listed, and Bar Julian's sunset comes with the key. 5. The Drayton or Andaz (Indagare's editors' pick) downtown; Hamilton-Turner Inn, Kehoe House, or The Gastonian if the trip calls for a four-poster in a mansion.",
    },
    {
      kind: "note",
      text: "One correction to old lists you'll find online: the Mansion on Forsyth Park no longer exists — it was gutted and reborn as Hotel Bardo in 2024. Same address, different century.",
    },
    {
      kind: "note",
      text: "With kids? It works better than the ghost-tour marketing suggests: the squares, the free Savannah Belles ferry across the river, Fort Pulaski, a Savannah Bananas game if the calendar cooperates, Leopold's ice cream (queue moves fast), and Perry Lane as base.",
    },
    {
      kind: "note",
      text: "When to go — Late October–November is the local answer: clear, cool, unhumid. Mid-March–April is azalea season and gorgeous, at peak prices — and avoid the weeks around St. Patrick's Day entirely unless you're coming for America's second-largest celebration. June–August is a feels-like-103° walking city, which is to say not one. September still swelters; it's also peak hurricane risk.",
    },
    {
      kind: "note",
      text: "The practical part — Fly into SAV, fifteen minutes from downtown. No car needed for Days 1–2 — the Historic District and Starland sit on one flat, walkable 2.5-mile spine with a free downtown shuttle. Rent or rideshare for Day 3–4 only. Book The Grey, Common Thread, and Brochu's when you book the flights. Mrs. Wilkes (the communal boardinghouse lunch) is real and good, but it's a 10am line, cash, weekdays — decide if that's your morning.",
    },
  ],
};
